### PR TITLE
Fix onPostParse return value not being used

### PR DESCRIPTION
**Pull request by coltonehrman**
## Checklist

- [x] Utilize onPostParse return value
- [x] Is this tested?

## Description

Set data variable to return value of onPostParse callback option

Added some simple test for onPostParse, could possibly use more extensive test cases

## References

#64 

## Notes

Noticed that `$.csv.toArrays` and `$.csv.toObjects` both utilize the onPostParse hook and essentially have duplicate code in them that could be cleaned up.

### CODE REVIEW

**Comment by evanplaice** [comment]
FYI, you should have push access now. Feel free to add your name to 'collaborators' in package.json. Let me know if you need a hand with testing.

**Comment by coltonehrman** [comment]
Ok thank you. I am having some weird issues with the tests running on my PC, specifically the csv.from_arrays.js tests are failing, it seems that the expect value has "\r\n" in it and the result value only has "\n" in it.

**Comment by evanplaice** [comment]
Unfortunately, that's the expected behavior for now. IIRC, there were a lot of users who had issues loading CSV files from OSX Excel (ie it spits out /r by default) so the parser implicitly replaces all line endings with `\n` because they work across all operating systems.

To fix it now would be API breaking. I'd like to change this behavior in 1.0 so a line ending other than `\n` will need to be configured manually in the options.

**Comment by evanplaice** [comment]
Nice work :+1:

Feel free to assign me as a reviewer if you want me to take a look before this merges. If you merge it yourself, do a squash+merge.

**Pull request merged**
